apiVersion: apps/v1
kind: Deployment

metadata:
  name: notes-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: notes

  template:
    metadata:
      labels:
        app: notes

    spec:
      containers:
      - name: notes-container
        image: notes-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
